version: "2.0"

nlu:
- intent: action::chop_cucumber
  examples: |
    - cucumber
    - chopped cucumber

- intent: action::chop_green_pepper
  examples: |
    - green pepper
    - green bell pepper
    - chopped green pepper

- intent: action::chop_onion
  examples: |
    - onion
    - red onion
    - slised onion

- intent: action::chop_tomato
  examples: |
    - tomato
    - chopped tomato

- intent: action::french_omelette
  examples: |
    - french omelette
    - I want to make a french omelette
    - Tell me the recipe of the french omelette
    - How can I make a french omelette?

- intent: action::greek_salad
  examples: |
    - greek salad
    - I want to make a greek salad
    - Tell me the recipe of the greek salad
    - How can I make a greek salad?

- intent: action::stir_eggs
  examples: |
    - stir eggs
    - blend eggs

- intent: question::ingr_am
  examples: |
    - how much [For extra taste you can add some red pepper, tomato and gouda cheese.]{"entity": "sort.ingredient", "value": "individual.extra_omelette_ingr"} do I need to use?
    - how much [Mint and oregano gives a really good taste in the salad]{"entity": "sort.ingredient", "value": "individual.extra_salad_ingr"} do I need to use?
    - how much [butter]{"entity": "sort.ingredient", "value": "individual.butter"} do I need to use?
    - how much [extra virgin oil]{"entity": "sort.ingredient", "value": "individual.oil"} do I need to use?
    - how much [feta cheese]{"entity": "sort.ingredient", "value": "individual.feta_cheese"} do I need to use?
    - how much [green olives]{"entity": "sort.ingredient", "value": "individual.olives"} do I need to use?
    - how much [oil]{"entity": "sort.ingredient", "value": "individual.oil"} do I need to use?
    - how much [olives]{"entity": "sort.ingredient", "value": "individual.olives"} do I need to use?
    - how much [vegetables]{"entity": "sort.ingredient", "value": "individual.vegetables"} do I need to use?
    - how much [vinegar]{"entity": "sort.ingredient", "value": "individual.vinegar"} do I need to use?
    - what is the amount of the [For extra taste you can add some red pepper, tomato and gouda cheese.]{"entity": "sort.ingredient", "value": "individual.extra_omelette_ingr"}?
    - what is the amount of the [Mint and oregano gives a really good taste in the salad]{"entity": "sort.ingredient", "value": "individual.extra_salad_ingr"}?
    - what is the amount of the [butter]{"entity": "sort.ingredient", "value": "individual.butter"}?
    - what is the amount of the [extra virgin oil]{"entity": "sort.ingredient", "value": "individual.oil"}?
    - what is the amount of the [feta cheese]{"entity": "sort.ingredient", "value": "individual.feta_cheese"}?
    - what is the amount of the [green olives]{"entity": "sort.ingredient", "value": "individual.olives"}?
    - what is the amount of the [oil]{"entity": "sort.ingredient", "value": "individual.oil"}?
    - what is the amount of the [olives]{"entity": "sort.ingredient", "value": "individual.olives"}?
    - what is the amount of the [vegetables]{"entity": "sort.ingredient", "value": "individual.vegetables"}?
    - what is the amount of the [vinegar]{"entity": "sort.ingredient", "value": "individual.vinegar"}?
    - how much [For extra taste you can add some red pepper, tomato and gouda cheese.]{"entity": "sort.ingredient", "value": "individual.extra_omelette_ingr"} should I use?
    - how much [Mint and oregano gives a really good taste in the salad]{"entity": "sort.ingredient", "value": "individual.extra_salad_ingr"} should I use?
    - how much [butter]{"entity": "sort.ingredient", "value": "individual.butter"} should I use?
    - how much [extra virgin oil]{"entity": "sort.ingredient", "value": "individual.oil"} should I use?
    - how much [feta cheese]{"entity": "sort.ingredient", "value": "individual.feta_cheese"} should I use?
    - how much [green olives]{"entity": "sort.ingredient", "value": "individual.olives"} should I use?
    - how much [oil]{"entity": "sort.ingredient", "value": "individual.oil"} should I use?
    - how much [olives]{"entity": "sort.ingredient", "value": "individual.olives"} should I use?
    - how much [vegetables]{"entity": "sort.ingredient", "value": "individual.vegetables"} should I use?
    - how much [vinegar]{"entity": "sort.ingredient", "value": "individual.vinegar"} should I use?

- intent: question::extra_ingr
  examples: |
    - Do you suggest any other ingredients?
    - Could you suggest me to add other ingredients?
    - I would like to add extra ingredients to the recipe, do you have any suggestions?

- intent: answer
  examples: |
    - [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - [vinegar]{"entity": "sort.ingredient", "value": "individual.vinegar"}
    - [feta cheese]{"entity": "sort.ingredient", "value": "individual.feta_cheese"}
    - [vegetables]{"entity": "sort.ingredient", "value": "individual.vegetables"}
    - [olives]{"entity": "sort.ingredient", "value": "individual.olives"}
    - [green olives]{"entity": "sort.ingredient", "value": "individual.olives"}
    - [oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - [extra virgin oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - [For extra taste you can add some red pepper, tomato and gouda cheese.]{"entity": "sort.ingredient", "value": "individual.extra_omelette_ingr"}
    - [Mint and oregano gives a really good taste in the salad]{"entity": "sort.ingredient", "value": "individual.extra_salad_ingr"}
    - [Amazing!French omelette is ready. Enjoy!]{"entity": "sort.ready", "value": "individual.omelette_finished"}
    - [Great job! Greek salad is ready. Enjoy!]{"entity": "sort.ready", "value": "individual.salad_finished"}
    - [one tablespoon of butter is enough]{"entity": "sort.amount", "value": "individual.butter_amount"}
    - [two tablespoons of vinegar is enough]{"entity": "sort.amount", "value": "individual.vinegar_amount"}
    - [you will need half cup of crumbled feta]{"entity": "sort.amount", "value": "individual.feta_cheese_amount"}
    - [you will need one tomato, half onion, half pepper and a whole cucumber]{"entity": "sort.amount", "value": "individual.vegetables_amount"}
    - [Olives are optional,but you can add some for extra taste]{"entity": "sort.amount", "value": "individual.olives_amount"}
    - [you should use half deciliter of oil]{"entity": "sort.amount", "value": "individual.oil_amount"}
    - [omelette]{"entity": "sort.recipe", "value": "individual.omelette"}
    - [salad]{"entity": "sort.recipe", "value": "individual.salad"}
    - yes [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - yes [Amazing!French omelette is ready. Enjoy!]{"entity": "sort.ready", "value": "individual.omelette_finished"}
    - no [vinegar]{"entity": "sort.ingredient", "value": "individual.vinegar"}
    - no [Great job! Greek salad is ready. Enjoy!]{"entity": "sort.ready", "value": "individual.salad_finished"}

- intent: answer_negation
  examples: |
    - not [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - not [vinegar]{"entity": "sort.ingredient", "value": "individual.vinegar"}
    - not [feta cheese]{"entity": "sort.ingredient", "value": "individual.feta_cheese"}
    - not [vegetables]{"entity": "sort.ingredient", "value": "individual.vegetables"}
    - not [olives]{"entity": "sort.ingredient", "value": "individual.olives"}
    - not [green olives]{"entity": "sort.ingredient", "value": "individual.olives"}
    - not [oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - not [extra virgin oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - not [For extra taste you can add some red pepper, tomato and gouda cheese.]{"entity": "sort.ingredient", "value": "individual.extra_omelette_ingr"}
    - not [Mint and oregano gives a really good taste in the salad]{"entity": "sort.ingredient", "value": "individual.extra_salad_ingr"}
    - not [Amazing!French omelette is ready. Enjoy!]{"entity": "sort.ready", "value": "individual.omelette_finished"}
    - not [Great job! Greek salad is ready. Enjoy!]{"entity": "sort.ready", "value": "individual.salad_finished"}
    - not [one tablespoon of butter is enough]{"entity": "sort.amount", "value": "individual.butter_amount"}
    - not [two tablespoons of vinegar is enough]{"entity": "sort.amount", "value": "individual.vinegar_amount"}
    - not [you will need half cup of crumbled feta]{"entity": "sort.amount", "value": "individual.feta_cheese_amount"}
    - not [you will need one tomato, half onion, half pepper and a whole cucumber]{"entity": "sort.amount", "value": "individual.vegetables_amount"}
    - not [Olives are optional,but you can add some for extra taste]{"entity": "sort.amount", "value": "individual.olives_amount"}
    - not [you should use half deciliter of oil]{"entity": "sort.amount", "value": "individual.oil_amount"}
    - not [omelette]{"entity": "sort.recipe", "value": "individual.omelette"}
    - not [salad]{"entity": "sort.recipe", "value": "individual.salad"}

- intent: NEGATIVE
  examples: |
    - aboard
    - about
    - above
    - across
    - after
    - against
    - along
    - among
    - as
    - at
    - on
    - atop
    - before
    - behind
    - below
    - beneath
    - beside
    - between
    - beyond
    - but
    - by
    - come
    - down
    - during
    - except
    - for
    - from
    - in
    - inside
    - into
    - less
    - like
    - near
    - of
    - off
    - on
    - onto
    - opposite
    - out
    - outside
    - over
    - past
    - save
    - short
    - since
    - than
    - then
    - through
    - throughout
    - to
    - toward
    - under
    - underneath
    - unlike
    - until
    - up
    - upon
    - with
    - within
    - without
    - worth
    - is
    - it
    - the
    - a
    - am
    - are
    - them
    - this
    - that
    - I
    - you
    - he
    - she
    - they
    - them
    - his
    - her
    - my
    - mine
    - their
    - your
    - us
    - our
    - how
    - how's
    - how is
    - how's the
    - how is the
    - when
    - when's
    - when is
    - when is the
    - when's the
    - what
    - what is
    - what's
    - what's the
    - what is the
    - why
    - why is
    - why's
    - why is the
    - why's the
    - do
    - make
    - tell
    - start
    - stop
    - enable
    - disable
    - raise
    - lower
    - decrease
    - increase
    - act
    - determine
    - say
    - ask
    - go
    - shoot
    - wait
    - hang on
    - ok
    - show
    - help

- intent: answer:yes
  examples: |
    - yes
    - yeah
    - yep
    - sure
    - ok
    - of course
    - very well
    - fine
    - right
    - excellent
    - okay
    - perfect
    - I think so

- intent: answer:no
  examples: |
    - no
    - nope
    - no thanks
    - no thank you
    - negative
    - don't want to
    - don't
    - do not
    - please don't

- intent: request:top
  examples: |
    - forget it
    - never mind
    - get me out of here
    - start over
    - beginning
    - never mind that
    - restart

- intent: request:up
  examples: |
    - go back
    - back
    - previous
    - back to the previous
    - go to the previous
    - go back to the previous one

- intent: request:how
  examples: |
    - how do I do that
    - how
    - can you tell me how to do that
    - I don't know how should I do that
    - how can I do that

- intent: report:done
  examples: |
    - I'm done
    - done
    - ready
    - it's ready
    - I'm ready
    - completed
    - check
    - I have finished
    - finished
    - done and done
    - it's done now
    - okay next
    - next
    - next instruction

- intent: icm:per*neg
  examples: |
    - repeat
    - repeat it
    - repeat that
    - pardon
    - sorry
    - can you repeat that
    - excuse me
    - what was that
    - what did you say
    - come again

- intent: icm:acc*neg:issue
  examples: |
    - I don't know
    - I don't know that
    - it doesn't matter

- intent: thanks
  examples: |
    - thank you
    - thank you very much
    - thanks
    - big thanks
    - thanks a lot

- intent: greet
  examples: |
    - hello
    - hi
    - good day
    - what's up
    - good evening
    - good morning
    - hey


